# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_user',
            old_name='IS_ACTIVE',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='m_user',
            old_name='USER_ID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='m_user',
            old_name='USER_NAME',
            new_name='user_name',
        ),
    ]
